device: "cpu"
seed: 11
env:
    env_name: "HalfCheetah-v4"
    num_envs: 120
    is_continuous: True
    state_dim: 17
    action_dim: 6
checkpoint_path: "checkpoints"
network:
    action_std_init: 0.1
    shared_layer: False
    optimizer:
        lr: 1e-4
        betas: [0.9, 0.999]
        eps: 1e-5
train: 
    total_timesteps: 5000000
    max_episode_len: 1024
    gamma: 0.99
    tau: 0.95
    ppo:
        loss_type: clip
        optim_epochs: 5
        batch_size: 3072
        eps_clip: 0.2
        coef_value_function: 0.5
        coef_entropy_penalty: 0.001
        value_clipping: False
    reward_scaler: True
    observation_normalizer: False
    clipping_gradient: True
    scheduler: True
    average_interval: 100
    max_ckpt_count: 3