device: "cpu"
seed: 77
env:
    env_name: "LunarLander-v2"
    is_continuous: False
    state_dim: 8
    action_dim: 4
checkpoint_path: "."
actor: 
    arch: [
        [nn.Linear, [state_dim, 64]],
        [nn.Tanh, []],
        [nn.Linear, [64, 64]],
        [nn.Tanh, []],
        [nn.Linear, [64, action_dim]],
        [nn.Softmax, [-1]]
    ]
    optimizer:
        lr: 0.002
        betas: [0.9, 0.999]
critic: 
    arch: [
        [nn.Linear, [state_dim, 64]],
        [nn.Tanh, []],
        [nn.Linear, [64, 64]],
        [nn.Tanh, []],
        [nn.Linear, [64, 1]]
    ]
    optimizer:
        lr: 0.002
        betas: [0.9, 0.999]
train: 
    max_episodes: 1500
    max_episode_len: 300
    gamma: 0.99
    tau: 0.95
    ppo:
        loss_type: clip
        optim_epochs: 4
        memory_size: 2048
        batch_size: 32
        eps_clip: 0.2
        coef_value_function: 0.5
        coef_entropy_penalty: 0.001
        value_cliiping: False
    clipping_gradient: True
    scheduler: False
    average_interval: 100
    log_interval: 100
    save_interval: 100